### ISSUE TITLE
jira init - 401 Unauthorized

### ISSUE THREAD

**Issue by akhiljalagam** [ankitpokhrel/jira-cli#439] opened 2022-08-16 04:37 UTC
**Describe the bug**

`jira init` failing with 401 Unauthorized response. but worked with curl requests using the same API token.

![image](https://user-images.githubusercontent.com/21128035/184798568-efe6021d-cc9c-4495-83d2-0745ff83223b.png)
 
**Please provide following details**
1. JiraCLI Version:
    ```
    (Version="v1.1.1-0.20220814163226-d993757c939c", GitCommit="", CommitDate="", GoVersion="go1.19", Compiler="gc", Platform="linux/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    Cloud
    ```
3. What operating system are you using? Also mention version.
    ```
    Void Linux
    ```
4. What terminal are you using? Also mention version.
    ```
    foot
    ```

**To Reproduce**

1. jira init

**Expected behavior**

should create config file.
**Screenshots**

**Additional context**

**Comment by ankitpokhrel** [comment] 2022-08-16 07:02
Hi @akhiljalagam, it looks like you haven't setup the token properly ([doc](https://github.com/ankitpokhrel/jira-cli/discussions/356)). If you are using personal access token (PAT), then you need to set `JIRA_AUTH_TYPE` to `bearer`.

**Comment by akhiljalagam** [comment] 2022-08-16 12:14
I tried both `bearer` and `basic`. didnt work.
but direct curl request working.

**Comment by viditsi1** [comment] 2022-08-17 14:23
Facing the same error. But I cannot seem to set my authentication method to bearer event after setting the env variable it is uses basic.

<img width="726" alt="image" src="https://user-images.githubusercontent.com/41787775/185159046-238549fb-39ea-461a-a526-a99e05dc507e.png">

**Comment by akhiljalagam** [comment] 2022-08-17 17:11
> Hey @akhiljalagam and @viditsi1 ! I had a similar problem but I found out that I made mistake while setting environmental variable. I tried first to add just `JIRA_API_ROKEN="xxxxxxxxxxxxxxxxxxxxx"` to my `.bashrc`. My `--debug init` gave similar result than yours. Then after 2 min Google I understood to add command `export` to the beginning of line. After that I ran command `source .bashrc`, and voilá, it's working! So make sure that your `.bashrc` file has a line like `export JIRA_API_ROKEN="xxxxxxxxxxxxxxxxxxxxx"`. and then run command `source .bashrc` . I hope it will work! :)

Thanks. But I always use `export` in my env files. @jaervei

**Comment by akhiljalagam** [comment] 2022-08-17 17:11
> Hey @akhiljalagam and @viditsi1 ! I had a similar problem but I found out that I made mistake while setting environmental variable. I tried first to add just `JIRA_API_ROKEN="xxxxxxxxxxxxxxxxxxxxx"` to my `.bashrc`. My `--debug init` gave similar result than yours. Then after 2 min Google I understood to add command `export` to the beginning of line. After that I ran command `source .bashrc`, and voilá, it's working! So make sure that your `.bashrc` file has a line like `export JIRA_API_ROKEN="xxxxxxxxxxxxxxxxxxxxx"`. and then run command `source .bashrc` . I hope it will work! :)

Thanks. But I always use `export` in my env files. @jaervei

**Comment by viditsi1** [comment] 2022-08-17 19:38
> Hey @akhiljalagam and @viditsi1 ! I had a similar problem but I found out that I made mistake while setting environmental variable. I tried first to add just `JIRA_API_ROKEN="xxxxxxxxxxxxxxxxxxxxx"` to my `.bashrc`. My `--debug init` gave similar result than yours. Then after 2 min Google I understood to add command `export` to the beginning of line. After that I ran command `source .bashrc`, and voilá, it's working! So make sure that your `.bashrc` file has a line like `export JIRA_API_ROKEN="xxxxxxxxxxxxxxxxxxxxx"`. and then run command `source .bashrc` . I hope it will work! :)

Its working for me now. Thanks for the help.

**Comment by ankitpokhrel** [comment] 2022-08-17 19:42
> But I cannot seem to set my authentication method to bearer event after setting the env variable it is uses basic.

@akhiljalagam  That means for some reason the app is not able to read env from your terminal. I think this is something related to your terminal `foot`, would you be able to check in other terminals?

**Comment by akhiljalagam** [comment] 2022-08-18 04:08
> > But I cannot seem to set my authentication method to bearer event after setting the env variable it is uses basic.
> 
> @akhiljalagam That means for some reason the app is not able to read env from your terminal. I think this is something related to your terminal `foot`, would you be able to check in other terminals?

Tried in `alacritty` and `kitty` terminals. same error.

**Comment by ankitpokhrel** [comment] 2022-08-18 06:48
That's weird! Since I cannot debug this on my side, let's try 2 things.

1. Try passing the env inline and see if it takes bearer token instead of basic

```sh
JIRA_AUTH_TYPE=bearer jira init --debug
```

2. Update the config manually to add auth type
    - Open your config file, you can get the path of config file from help `jira -h`
    - Add a line `auth_type: bearer`, save the file.
    - Run `jira init --debug` and see if it takes bearer token

**Comment by akhiljalagam** [comment] 2022-08-18 08:57
> That's weird! Since I cannot debug this on my side, let's try 2 things.
> 
>     1. Try passing the env inline and see if it takes bearer token instead of basic
> 
> 
> ```shell
> JIRA_AUTH_TYPE=bearer jira init --debug
> ```
> 
>     2. Update the config manually to add auth type
>        
>        * Open your config file, you can get the path of config file from help `jira -h`
>        * Add a line `auth_type: bearer`, save the file.
>        * Run `jira init --debug` and see if it takes bearer token

no luck.

still same response.
`Authorization: Bearer`

**Comment by ankitpokhrel** [comment] 2022-08-18 09:21
> still same response.
> Authorization: Bearer

Does this mean you can see the request using bearer token now in the log?

**Comment by akhiljalagam** [comment] 2022-08-18 09:35
> > still same response.
> > Authorization: Bearer
> 
> Does this mean you can see the request using bearer token now in the log?

Yes.

**Comment by ankitpokhrel** [comment] 2022-08-18 09:42
Alright now try passing `JIRA_API_TOKEN` in the same manner either inline or in the config as `api_token: <token>` and set `JIRA_AUTH_TYPE` based on if you are using basic or bearer auth. I think it should work.

**Comment by akhiljalagam** [comment] 2022-08-18 09:45
great. finally this worked for me. thanks @ankitpokhrel 
```
JIRA_API_TOKEN=<token>  JIRA_AUTH_TYPE=basic jira init --debug
```

**Comment by ankitpokhrel** [comment] 2022-08-18 09:52
Awesome! This clearly means the way you were setting the env before has issue. It is for some reason not getting reflected in a subshell. Closing this issue since you can use a workaround.

**Closed by ankitpokhrel** 2022-08-18 09:52 UTC

**Comment by akhiljalagam** [comment] 2022-08-18 10:33
@ankitpokhrel 
I don't think so. I always used `export` and verfied with `echo` but something wrong with `jira` command the way it is getting variable.I guess.

**Comment by e455a81e-d3ba-41a2-bc6d-7aafb1d9a5cd** [comment] 2022-08-20 20:32
I can confirm this issue on Ubuntu 20.04, supplying the api token inline works; but setting the token via `export `or `bashrc `does not.

**Comment by tomerika** [comment] 2022-08-21 06:50
> great. finally this worked for me. thanks @ankitpokhrel
> 
> ```
> JIRA_API_TOKEN=<token>  JIRA_AUTH_TYPE=basic jira init --debug
> ```

For me - this works for getting authenticated successfully (it shows me the list of projects, I select mine successfully)

Then I try to run some command(s) and I get various errors:

1. for `jira issue list` / `jira epic list` I get :
jira: Received unexpected response '400 Bad Request'

2. for `jira issue create ...` I get:
Error:
  - You do not have permission to create issues in this project.
jira: Received unexpected response '401 Unauthorized'.
Please check the parameters you supplied and try again.

It may be something I've done, as I've tweaked some user settings in Jira and then I found myself disconnected from jira-cli.
I then saw somewhere in their documentation that normal authentication (which I believe is `basic` as recommended above) is not supported anymore (so I'm surprised that worked..?)

@ankitpokhrel - got a suggestion for me to try?
btw I've been using it for some time - awesome work on this one!

**Comment by akhiljalagam** [comment] 2022-08-22 05:03
@ankitpokhrel Re-Open this issue, please.

**Comment by tomerika** [comment] 2022-08-24 07:25
Ok, apparently it was my bad - by that point of trying to debug I've had 
`export JIRA_AUTH_TYPE="bearer"`
in my .zshrc which made it not work

Here's how to handle if anyone is facing it:
inside your .zshrc include this:
export JIRA_API_TOKEN="<insert token here>"
(to create a token go to:
https://id.atlassian.com/manage-profile/security/api-tokens)

(make sure you don't have
export JIRA_AUTH_TYPE="bearer" in your zshrc
apparently, bearer token should not be used)

**Comment by e455a81e-d3ba-41a2-bc6d-7aafb1d9a5cd** [comment] 2022-08-24 12:59
I just tried it again using an executable that I built myself from the current main branch. It now seems to work for me.

**Comment by alkoclick** [comment] 2023-03-08 10:18
I had various issues with hitting 401s, and this thread was the closest thing I found (and also had some helpful debugging). I use JIRA Cloud with my org's SSO. For me what worked was generating a PAT, then using basic authentication, so my exports looks like this:

```
export JIRA_API_TOKEN="REDACTED"
export JIRA_AUTH_TYPE="basic"
```

**Comment by zph** [comment] 2024-07-11 04:02
Adding yet another solution:

I received 401 for Cloud when org uses SSO when using the vanity dns entry used for Jira.

I ran curl against that endpoint with `-L` to follow redirects until it reached the terminal domain/subdomain combination and used that when running jira init and it worked when combined with JIRA_API_TOKEN=<secret> and without JIRA_AUTH_TYPE.
