### ISSUE TITLE
`brew upgrade` failing on 1.0.0-beta

### ISSUE THREAD

**Issue by BergQuester** [ankitpokhrel/jira-cli#361] opened 2022-05-10 18:50 UTC
**Describe the bug**

I have Xcode 13.3.1 installed and set as the command line tools. On upgrading via brew I get the following:

```
==> Upgrading ankitpokhrel/jira-cli/jira-cli
  0.3.0 -> 1.0.0-beta

Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.3.
```

**Please provide following details**
1. JiraCLI Version:
    ```
    1.0.0-beta
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    N/A
    ```
3. What operating system are you using? Also mention version.
    ```
    macOS Monterey 12.3.1
    ```
4. What terminal are you using? Also mention version.
    ```
    iTerm 2 Build Build 3.4.15
    ```

**To Reproduce**

1. Have Xcode 13.3.1 installed and set to the command line tools
2. Have an older version of jira-cli installed3. 
3. Run `brew upgrade`

**Expected behavior**
The tools version test passes as 13.3.1 should meet the requirement for 13.3

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Drowze** [comment] 2022-05-11 16:38
Just adding details for this ticket: I just ran `brew upgrade` and it worked fine here on my local.

brew output:
```
==> Upgrading ankitpokhrel/jira-cli/jira-cli
  0.3.0 -> 1.0.0-beta

🍺  /usr/local/Cellar/jira-cli/1.0.0-beta: 4 files, 16.9MB, built in 4 seconds
==> Running `brew cleanup jira-cli`...
Removing: /usr/local/Cellar/jira-cli/0.3.0... (4 files, 16.6MB)
```

OS version: `macOS Big Sur 11.6`
Xcode version: `version: 13.2.0.0.1.1638488800` (only `CommandLineTools` installed, checked version via [this SO answer](https://stackoverflow.com/questions/21272479/how-can-i-find-out-if-i-have-xcode-commandline-tools-installed/42144725#42144725))
Terminal: `Alacritty 0.10.1`

**Comment by BergQuester** [comment] 2022-05-11 17:42
What's weird is I just tried installing the 13.3.1 command line tools package from the developer site and that worked around the issue.

Strange, since my original setup should have worked.

**Comment by ankitpokhrel** [comment] 2022-05-12 06:09
Just checked in my local machine `macOS Big Sur 11.6` on `XCode 13.1`, `brew upgrade` ran without any issues.

I don't think this is related to `jira-cli` since I've noticed some of my colleagues have similar issue but with other tools. Let's keep this issue open for a while just in case.

**Comment by ankitpokhrel** [comment] 2022-07-05 06:38
Closing due to inactivity and I can't reproduce the issue. Please feel free to comment or open a new issue if you think the problem still persists.

**Closed by ankitpokhrel** 2022-07-05 06:38 UTC
Labels: not sure if 🤔
