### ISSUE TITLE
Failed to load module "window-decorations-gtk-module"

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [ankitpokhrel/jira-cli#653] opened 2023-08-14 03:47 UTC
**Describe the bug**

**Please provide following details**
1. JiraCLI Version:
    ```
    1.4.0-1
    ```
2. Are you using Jira cloud or on-premise jira server?
    ```
    Cloud

    SERVER INFO
    -----------
    Version:         1001.0.0-SNAPSHOT
    Build Number:    100234
    Deployment Type: Cloud
    Default Locale:  en_US
    ```
3. What operating system are you using? Also mention version.
    ```
    Arch Linux (23.08.14)
    ```
4. What terminal are you using? Also mention version.
    ```
    Kitty 0.29.2-1
    ```

**To Reproduce**

1. $jira issue list
2. <enter> on any listed issue
3. See error appearing between lines of listed issues

**Expected behavior**

No error messages / <enter> opens issue

**Comment by colindean** [comment] 2023-08-16 20:49
Effectively a dupe of #547

**Comment by ankitpokhrel** [comment] 2024-04-06 10:16
Closing as this seems to be system dependent and out of scope of this project.

**Closed by ankitpokhrel** 2024-04-06 10:16 UTC
