### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by Poil** [ankitpokhrel/jira-cli#118] opened 2021-07-30 13:18 UTC
Hi,

I've got this error when trying to install

```
$ go get github.com/ankitpokhrel/jira-cli/cmd/jira
package github.com/russross/blackfriday/v2: cannot find package "github.com/russross/blackfriday/v2" in any of:
	/usr/lib/go-1.13/src/github.com/russross/blackfriday/v2 (from $GOROOT)
	/home/bdupuis/go/src/github.com/russross/blackfriday/v2 (from $GOPATH)
```

Installing after installing blackfriday v2 works
```
go get github.com/russross/blackfriday/v2
```

Best regards,

**Comment by ankitpokhrel** [comment] 2021-08-04 20:53
Hi @Poil I am not able to reproduce the issue. I tried with go1.13 (and above) and the installation seems to be working fine. Could you please provide more context?

**Comment by dja-fr** [comment] 2021-09-08 09:55
Hello,

Same here :

```
go get github.com/ankitpokhrel/jira-cli/cmd/jira
cannot find package "github.com/russross/blackfriday/v2" in any of:
        c:\go\src\github.com\russross\blackfriday\v2 (from $GOROOT)
        C:\Users\dja\go\src\github.com\russross\blackfriday\v2 (from $GOPATH)
cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
        c:\go\src\github.com\hashicorp\hcl\hcl\printer (from $GOROOT)
        C:\Users\dja\go\src\github.com\hashicorp\hcl\hcl\printer (from $GOPATH)
```

My environnement 

- windows
- go version 1.15.7

Could be related to : https://github.com/russross/blackfriday/issues/500 ?

**Comment by ankitpokhrel** [comment] 2021-12-31 11:35
I think we don't have this issue when using `go install` which is now a recommended way to install the executables.

From [the docs](https://tip.golang.org/doc/go1.16#modules):
> go install, with or without a version suffix (as described above), is now the recommended way to build and install packages in module mode. go get should be used with the -d flag to adjust the current module's dependencies without building packages, and use of go get to build and install packages is deprecated. In a future release, the -d flag will always be enabled.

Also, since there are executables available for supported platforms now (see [releases](https://github.com/ankitpokhrel/jira-cli/releases)), installation should not be a problem.

I will close this issue but feel free to comment if you feel like this topic is unanswered.

**Closed by ankitpokhrel** 2021-12-31 11:35 UTC
Labels: help | support
